name: Build Windows app

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build in venv
        shell: pwsh
        run: |
          python -m venv .venv
          . .\.venv\Scripts\Activate.ps1
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          "Yes" | pyside6-deploy -f

      - name: Show deployment output
        shell: pwsh
        run: |
          Get-ChildItem -Recurse deployment

      - name: Upload deployment folder
        uses: actions/upload-artifact@v4
        with:
          name: fitbit_qt-windows
          path: deployment
